# Generated by Django 4.2.3 on 2023-08-02 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_task_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user_id',
            new_name='user',
        ),
    ]
